In [8]:
# required imports
import numpy as np
import fnmatch
import os
import sys

file_count = 0             # file_count to count number of files
files_dict = {}            # files_dic to store count of every file    
unique_word_set = set()    # unique_word_set to store all the unique words in a set
root_directory = 'E:\Semester 06\Machine Learning_ML\IRS_Assignment no 02\BCSF20M503_IRS_Solution\Data_file' #telling the path of the directory where data files are contained

for subdir, dirs, files in os.walk(root_directory): #os.walk() is used to traverse all the directories including root directory
    for file in files:
        file_count+=1   #counting all the files 
        file_path = os.path.join(subdir, file) #os.path.join() is used to generate full path to the file
        fname = open(file_path, 'r') #open is used to open the file using its path in r means reading mode
        word = fname.read() #read() reads the file and stores the result as a string
        temp = word.split() #splits the words on whitespaces and stores in temporary variable temp
        files_dict[file] = len(temp) #counts the splitted words, and stores in files_dict
        unique_word_set.update(temp) #update fuction updates the values in a set. Here when splitting the words adding them side by side in a set
        
print("\nTotal Number  of files\n", file_count)
print("\nDictionary containing  files\n", files_dict)
print("\nUnique words in every file\n", unique_word_set)

row_file = file_count # no of rows equal to total no of files
col_word = len(unique_word_set) #no of cols equal to total unique words
term_doc_matrix = np.zeros((row_file,col_word)) #initializing term_doc_matrix with zero
print(term_doc_matrix)

dict_for_unique_words = {} # in this dict, each word is a key, and corresponding index is the value
dict_for_unique_words =  {word: index for index, word in enumerate(unique_word_set)} #the enumerate() function is used to iterate over the words in the set, along with their corresponding index starting from 0
print("\nDictionary of unique words\n", dict_for_unique_words)

dict_for_files = {}
dict_for_files =  {file: index for index, file in enumerate(files)} #the enumerate() function is used to iterate over the words in the set, along with their corresponding index starting from 0
print("\nDictionary of files\n", dict_for_files)

for i, file in enumerate(files): #Loop through each file
    f = open(file, 'r')
    file_contents = f.read()  #Reading the file contents
    words = file_contents.split() #Split the file contents into words
    for word in words: #Loop through each word in the file
        if word in dict_for_unique_words: #Check if the word is in the set of unique words
            word_index = dict_for_unique_words[word] #Get the index of the word
            term_doc_matrix[i][word_index] = 1 #Set the corresponding value in the matrix to 1
print(term_doc_matrix)

col_vector = np.zeros((len(unique_word_set),1))   #initializing column_vector with zero
print(col_vector)

query = input("\nWrite something for searching:  ")  #Asking for user input
for word in query.split(): #Split query into words and check if each word is in unique_words
    if word in dict_for_unique_words: #If the word is in unique_words, increment the corresponding count in column_vector
        col_vector[dict_for_unique_words[word]] += 1 
    else:
        print('Such query is not found in the data files')
        sys.exit()
print(col_vector)

resultant_vector = np.dot(term_doc_matrix,col_vector) #res_vector is obtained by taking dot product of term_doc_matrix and col_vector
print('\nResultant Vector is: \n', resultant_vector)
max_value = max(resultant_vector)   #finding max_value in res_vector
print('\nMax value is: \n', max_value)
max_index = np.argmax(resultant_vector) #finding index of that max_value using argmax
print('\nIndex of Max value is: \n', max_index)

max_file_name = files[max_index]  #finding the file having max value in resultant vector
f = open(max_file_name, 'r')
file_contents = f.read()  #reading that file contents
print(f"File with maximum value: {max_file_name}\n")
print(file_contents)  #printing that contents


Total Number  of files
 3

Dictionary containing  files
 {'f1.txt': 4, 'f2.txt': 4, 'f3.txt': 4}

Unique words in every file
 {'This', 'book', 'My', 'pen', 'interesting', 'my', 'is'}
[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]

Dictionary of unique words
 {'This': 0, 'book': 1, 'My': 2, 'pen': 3, 'interesting': 4, 'my': 5, 'is': 6}

Dictionary of files
 {'f1.txt': 0, 'f2.txt': 1, 'f3.txt': 2}
[[1. 1. 0. 0. 0. 1. 1.]
 [1. 0. 0. 1. 0. 1. 1.]
 [0. 1. 1. 0. 0. 0. 1.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]

Write something for searching:  pen
[[0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]]

Resultant Vector is: 
 [[0.]
 [1.]
 [0.]]

Max value is: 
 [1.]

Index of Max value is: 
 1
File with maximum value: f2.txt

This is my pen
